"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import cx_Freeze

executables = [cx_Freeze.Executable("gameclass.py")]

cx_Freeze.setup(
    name="2D Mario Kart",
    options={"build_exe": {"packages":["pygame"],
                           "include_files":["bowser.png", "donkeykong.png", "toad.png", "toadette.png", "yoshi.png", "waluigi.png"]}},
    executables = executables

    )
